#!/bin/bash
echo "Remember to make first!"
echo "Copying html to ntris.mit.edu..."
scp index.html linerva.mit.edu:~/www/ntris.html
echo "Copying swf to ntris.mit.edu..."
scp Board.swf linerva.mit.edu:~/www/.
